### ISSUE TITLE
Text color too dark for new files

### ISSUE THREAD

**Issue by LemuelPuglisi** [marqu3ss/Aurora-X#1]
New files color is too dark, so they hide in the background. 
I think using some other colors like green or whatelse will improve UX. 

![image](https://user-images.githubusercontent.com/42694683/78471744-e52a1800-7733-11ea-9321-2b02d4e822c5.png)

Anyway, best VScode theme! Keep pushin

**Comment by marqu3ss** [comment]
Thanks for the feedback, It will be improved for the next release :)

**Comment by WillMuzyka** [comment]
I was coming here to make the same issue, it's to dark to read the new files. A green-ish color would be amazing, adding contrast to it (but this is only my preference).
And really nice work, amazing theme!
