### ISSUE TITLE
Terminal has no upper border

### ISSUE THREAD

**Issue by maeriens** [marqu3ss/Aurora-X#2]
When I have the terminal open, I cannot find where the terminals end, as they have the same border and background color.
In this screenshot, I have two terminals one next to the other, and at the top there is the code - it becomes very hard to resize or move them around 
![image](https://user-images.githubusercontent.com/5074186/83476695-beecd400-a467-11ea-9087-d08e6f0b8764.png)

**Comment by marqu3ss** [comment]
Thank you for the feedback :)

There are some borders missing in general, once implemented (next release) it will easier see the limitations on each panel of VScode.
