### ISSUE TITLE
File color different after git add.

### ISSUE THREAD

**Issue by jordanjlatimer** [marqu3ss/Aurora-X#6]
First off, I just want to say that I love this theme.

Secondly, it looks like the color of files in the file explorer is different before and after doing "git add".

Here is what it looks like before:
![Screen Shot 2020-12-08 at 6 25 27 PM](https://user-images.githubusercontent.com/48840937/101561659-f68e8880-3982-11eb-8c29-ea16cd8bb446.png)

And after:
![Screen Shot 2020-12-08 at 6 25 59 PM](https://user-images.githubusercontent.com/48840937/101561662-f7271f00-3982-11eb-9251-47d904be5aca.png)

I didn't know if this is intended behavior or not.

**Comment by mgilardi** [comment]
@jordanjlatimer I have nothing to do with the development of the theme, but, if that's happening after 'git add' it's probably differentiating between staged/unstaged files. My guess is that it's intended, as it can be useful to know which files are staged for commit if you don't want all at once.
